### ISSUE TITLE
no such file to load -- win32ole when running .exe but not ruby script

### ISSUE THREAD

**Issue by kodemonkee** [larsch/ocra#53] opened 2012-11-17 09:29 UTC
Local dev box is Windows XP SP3

ruby 1.8.7 (2012-10-12 patchlevel 371) [i386-mingw32]
gem -v => 1.8.24

gem list:
actionmailer (2.3.4)
actionpack (2.3.4)
activerecord (2.3.4)
activeresource (2.3.4)
activesupport (2.3.4)
builder (3.1.4)
cgi_multipart_eof_fix (2.5.0)
commonwatir (1.6.5)
daemons (1.0.10)
fastercsv (1.5.0)
fastthread (1.0.7)
ffi (1.1.5 x86-mingw32)
firewatir (1.6.5)
gem_plugin (0.2.3)
hoe (3.3.0)
i18n (0.6.1)
mongrel (1.1.5)
multi_json (1.3.7)
mysql (2.7.3 mswin32)
net-ssh (2.0.14)
nokogiri (1.5.5 x86-mingw32)
ocra (1.3.0)
rack (1.0.1)
rails (2.3.4)
rake (0.8.7)
rubygems-update (1.3.5)
s4t-utils (1.0.4)
sequel (3.0.0)
user-choices (1.1.6.1)
watir (1.6.5)
will_paginate (2.3.12)
win32-api (1.4.8 x86-mingw32)
win32-process (0.5.5)
windows-api (0.4.2)
windows-pr (1.2.2)
xml-simple (1.1.2)

script works as expected on local dev machine.  Use OCRA to create .exe, run .exe on local dev machine and the following error is encountered:

...custom_require.rb:36:in `gem_original_require': no such file to load -- win32ole (LoadError)

script excerpt where this is being called out is on require statement:

require 'win32ole'

autoit = WIN32OLE.new("AutoItX3.Control")

**Comment by larsch** [comment] 2017-10-14 21:59
Closing - unable to reproduce.

**Closed by larsch** 2017-10-14 21:59 UTC
Labels: need-info
